### ISSUE TITLE
updateWeekView function doesn't exist on component's ref

### ISSUE THREAD

**Issue by MargaretKrutikova** [BugiDev/react-native-calendar-strip#102]
As stated in the README:

> updateWeekView(date, startDate) | Show the week that includes the date param. If startDate is provided, the first day of the week resets to it as long as useIsoWeekday is false.

but the method doesn't exist on the component's `ref`. A similar method called `updateWeekData` is accessible but it doesn't seem to update the component since it doesn't set anything on the `state`  and only returns the new updated `state` object.

I see that method `updateWeekView` existed before but got removed [here](https://github.com/BugiDev/react-native-calendar-strip/commit/a7e30494ddfdfd791bd1d81ea69c802fd07d7b33#diff-9aeb396ee5707a96899dd7467eb0a662R219) together with some refactoring and optimization. Is it possible to restore it? :) I need to implement a possibility to jump back to the current week in the calendar and that's exactly where that method would be useful.

**Comment by peacechen** [comment]
That should be updated or removed from the docs.  That method was obsoleted by the `startingDate` prop.  Update that prop to change the displayed week.

It's been a while, but IIRC the `updateWeekView` opened up a lot of corner cases because the other props would be stale (e.g. update week to another week, but startingDate is still the previous week).

**Comment by peacechen** [comment]
The `updateWeekView` method has been restored in 2.0.0.
