### ISSUE TITLE
Selection "background" is cut off

### ISSUE THREAD

**Issue by mintotsai** [BugiDev/react-native-calendar-strip#22]
```
<CalendarStrip
     style={{paddingTop: 20, paddingBottom: 10}}`
     calendarAnimation={{type: 'parallel', duration: 300}}
     selection={'background'}
     selectionAnimation={{duration: 300, borderWidth: 2}}
     calendarHeaderStyle={{color: 'white'}}
     calendarColor={'#7743CE'}
     highlightColor={'#9265DC'}
     highlightDateNumberStyle={{color: 'white'}}
     highlightDateNameStyle={{color: 'white'}}
     dateNumberStyle={{color: 'white'}}
     dateNameStyle={{color: 'white'}}
     borderHighlightColor={'white'}
     iconLeft={require('../Images/left-arrow.png')}
     iconRight={require('../Images/right-arrow.png')}
     iconContainer={{flex: 0.1}}
/>
```

![glass_and_iphone_7_ _ios_10_2__14c89_](https://cloud.githubusercontent.com/assets/1557318/23073832/5cf8d7da-f4fc-11e6-9277-b3f3133d1315.png)

**Comment by peacechen** [comment]
This is in part a symptom of the calendar strip not being truly responsive.  The dates and highlights should scale down as the component size decreases.

You may be able to work around that by disabling weekend styling
```
styleWeekend={false}
```

**Comment by mintotsai** [comment]
Unfortunately, that doesn't help. I see an issue created for this, so I'll close it.

Dupe: [](https://github.com/BugiDev/react-native-calendar-strip/issues/14)

**Comment by lbrdar** [comment]
Hi guys,

I have the same problem in my project and it's because the default background of CalendarDay component is calendarColor and, because CalendarDay component overlap, this cut out happens. 

I believe that using 
`let dateViewBGColor = this.state.selected ? this.props.daySelectionAnimation.highlightColor : 'transparent';`
instead of 
`let dateViewBGColor = this.state.selected ? this.props.daySelectionAnimation.highlightColor : 'this.props.calendarColor';`
in line 104 of CalendarDay component would solve this problem. Is there any specific reason why you are not using transparent but calendarColor for days that aren't selected?

Thank you,
Leo

**Comment by peacechen** [comment]
@lbrdar That looks like a good suggestion.  Please create a PR and I'll test & merge.

**Comment by peacechen** [comment]
Thanks for the PR @lbrdar .  Merged and will release a new version on npm.

**Comment by peacechen** [comment]
v1.2.0 implements responsive sizing
