### ISSUE TITLE
selectedDate prop change not updating state

### ISSUE THREAD

**Issue by ganesh-papola** [BugiDev/react-native-calendar-strip#249]
Is. there any prop for value, as selectedDate is not working when changing its value?

**Comment by Vasault** [comment]
startingDay, but really, what exactly you looking for?

**Comment by peacechen** [comment]
After looking through the code, there is a bug with `selectedDate` prop updates. It's not updating state on a change.

https://github.com/BugiDev/react-native-calendar-strip/blob/master/src/CalendarStrip.js#L146

Please submit a PR to add selectedDate to `componentDidUpdate()`. It should perform the same checks as it does for `startingDate` because the prop may come in as a string, JS Date, or Moment date.

**Comment by peacechen** [comment]
Fix published in 2.1.2
