### ISSUE TITLE
[Android] Selected CalendarDay cut off on small width screen

### ISSUE THREAD

**Issue by luugiathuy** [BugiDev/react-native-calendar-strip#45]
Hi, 

Please see the attached screenshot below. This happens on my Nexus 5 emulator.

![screen shot 2017-08-03 at 1 12 56 am](https://user-images.githubusercontent.com/656820/28885613-1a981a0c-77e9-11e7-8886-e6fa971d8269.png)

I was trying to set the zIndex for the selected CalendarDay but it not work. Do you have any idea how to fix this? Thank you for your library.

**Comment by peacechen** [comment]
It may be that the responsive sizing is setting the border size too large.  Which version of CalendarStrip are you using?

**Comment by peacechen** [comment]
Since there are differences between Android and iOS layout sizing, I added the prop `responsiveSizingOffset` to adjust the computed day component size.  Experiment with negative values to decrease the day sizes.  `-5` may be a good start.

You'll need to pull from this repo directly until this change is published to npm.
```
  "dependencies": {
    "react-native-calendar-strip": "https://github.com/BugiDev/react-native-calendar-strip",
  },
```

**Comment by luugiathuy** [comment]
@peacechen Hi! I'm running the example app. I checked its package.json, it use the updated master branch. Let me check with your commit. Thanks!

**Comment by peacechen** [comment]
Did `responsiveSizingOffset` help fit the border?

**Comment by luugiathuy** [comment]
@peacechen It works but then I have to manually set it. However on some phone with higher width than Nexus 5, the font of dateName of dateNumber looks small. Is there any way we can automatically set the responsiveSizingOffset based on device width?

**Comment by luugiathuy** [comment]
@peacechen I found a good way to resolve this issue. I calculate the `maxDayComponentSize = (screenWidth - (iconWidth * 2)) / 7;` and set this `maxDayComponentSize` prop for Android only. It works now. Thank you!

**Comment by peacechen** [comment]
@luugiathuy  Glad to hear that you found a workable solution.  CalendarStrip's magic number divisors used in `onLayout` should be added as props so that users can better customize the sizing behavior.
https://github.com/BugiDev/react-native-calendar-strip/blob/master/src/CalendarStrip.js#L481

If you have any suggestions on how it should behave or what knobs should be added, feel free to follow up here or create another issue.
