### ISSUE TITLE
_moment2.default.add is not a function.

### ISSUE THREAD

**Issue by BurhanMughal** [BugiDev/react-native-calendar-strip#56]
Above error occurs while adding days to whitelist 
> **moment.add(3, 'days')**
Can you please help?

**Comment by peacechen** [comment]
Just saw this, apologies for the delayed reply. That was a typo in the Readme. 
`moment` is not a date instance, it's the library.  A date instance containing the current datetime may be created with `moment()`. Then you could call
`moment().add(3, 'days')`

It's better practice to store the current date in a variable.  Performance in a loop is the same since a copy has to be made every time (`add` mutates the date), but it prevents the datetime from changing every call.  An example corner case is on a date boundary at midnight.  If the loop starts just before midnight, it would give one date, but if the loop ends just after midnight, some elements in the loop may get the subsequent date.  So do this instead:
```
    let today = moment();
    let datesWhitelist = [{
      start: today,
      end: today.clone().add(3, 'days')  // total 4 days enabled
    }];
    let datesBlacklist = [ today.clone().add(1, 'days') ]; // 1 day disabled
```
