### ISSUE TITLE
how disabled all days before current day

### ISSUE THREAD

**Issue by ayaansar** [BugiDev/react-native-calendar-strip#60]
Hi!Thanks,great work!
I have some problem with taking days before today.
If do like that,disabled only one day before current day
let datesBlacklist = [ moment().subtract(2, 'day') ]
...
<CalendarStrip
    ...
   datesBlacklist={datesBlacklist} />

**Comment by peacechen** [comment]
Please refer to the props documentation
https://github.com/BugiDev/react-native-calendar-strip#initial-data-and-ondateselected-handler

A Date object in the array indicates a single day (disabled in the case of datesBlacklist).  In order to specify a range, provide an entry that's an object in this form:
```
{
    start: (Date or moment Date)
    end: (Date or moment Date)
}
```

**Comment by TemirlanKudabayev** [comment]
thank you!
